#Impostazioni di gioco configurabili (in stile Minecraft)
#Thu Jun 04 22:56:36 CEST 2026
camera_zoom=0.72
default_player_speed=200.0
dev_mode=true
draw_physics_debug=true
max_player_distance=400.0
music_volume=0.5
player_size=160.0
sfx_volume=0.5
